.. shared links for documentation
    vim: ft=rst

.. _bt00l: http://www.gerg.ca/software/btOOL
.. _btparse: http://search.cpan.org/dist/btparse
.. _Text-BibTeX: http://search.cpan.org/dist/Text-BibTeX

.. _Nelson Beebe's bibliography tools: http://www.math.utah.edu/~beebe/software/bibtex-bibliography-tools.html
.. _bibclean: http://www.math.utah.edu/~beebe/software/bibclean
.. _bibparse: http://www.math.utah.edu/~beebe/software/bibparse
.. _bibtex_to_html.awk: http://www.netlib.org/bibnet/tools/software/bibtex-to-html.awk
.. _bibparse grammar: http://www.math.utah.edu/~beebe/software/bibparse/bibparse.html#HDR.5
.. _bibclean grammar description: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.101.8005&rep=rep1&type=pdf

.. _bibtex.org format description: http://www.bibtex.org/Format
.. _Dana Jacobsen's bibtex format overview: http://www.fb10.uni-bremen.de/anglistik/langpro/bibliographies/jacobsen-bibtex.html
.. _Xavier Decoret's bibtex summary: http://artis.imag.fr/~Xavier.Decoret/resources/xdkbibtex/bibtex_summary.html

.. _bibstuff: http://pricklysoft.org/software/bibstuff.html
